# Generated by Django 4.2.4 on 2023-09-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_breeds_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
